// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9j3mKUPi2D4lhpnYfhM7tbbWkxpBPtRo',
    appId: '1:693735469562:web:f1d294471daddaf7b3b443',
    messagingSenderId: '693735469562',
    projectId: 'notepad-98213',
    authDomain: 'notepad-98213.firebaseapp.com',
    storageBucket: 'notepad-98213.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0yQ3c577OWWqt1VtkCpWSm62vZTUCBQc',
    appId: '1:693735469562:android:b9ce0119075e4006b3b443',
    messagingSenderId: '693735469562',
    projectId: 'notepad-98213',
    storageBucket: 'notepad-98213.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2q49zCi0AV3Uhdjasu2v_kAKUzAIXR1M',
    appId: '1:693735469562:ios:b9bbd101db9e1f50b3b443',
    messagingSenderId: '693735469562',
    projectId: 'notepad-98213',
    storageBucket: 'notepad-98213.firebasestorage.app',
    iosBundleId: 'com.example.notepad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2q49zCi0AV3Uhdjasu2v_kAKUzAIXR1M',
    appId: '1:693735469562:ios:b9bbd101db9e1f50b3b443',
    messagingSenderId: '693735469562',
    projectId: 'notepad-98213',
    storageBucket: 'notepad-98213.firebasestorage.app',
    iosBundleId: 'com.example.notepad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9j3mKUPi2D4lhpnYfhM7tbbWkxpBPtRo',
    appId: '1:693735469562:web:17ef2949ef1a3b07b3b443',
    messagingSenderId: '693735469562',
    projectId: 'notepad-98213',
    authDomain: 'notepad-98213.firebaseapp.com',
    storageBucket: 'notepad-98213.firebasestorage.app',
  );

}